# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2023-05-14 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='misionempresa',
            table='misiones',
        ),
    ]
