# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2023-05-14 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20230514_0902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MisionEmpresa',
            new_name='Misiones',
        ),
        migrations.AlterModelTable(
            name='misiones',
            table=None,
        ),
    ]
