# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2023-05-14 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20230514_1124'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='misiones',
            table='my_app_misiones',
        ),
    ]
