# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2023-05-31 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20230514_1227'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='misiones',
            table='estadisticas',
        ),
    ]
