# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2023-05-31 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20230531_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadisticas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=50)),
                ('tipodiscapacidad', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('actividadeconomica', models.CharField(max_length=100)),
                ('categoriaocupacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Misiones',
        ),
    ]
