# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2023-06-01 00:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_auto_20230531_2322'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estadisticas',
            table='my_app_estadisticas',
        ),
    ]
