# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2023-06-01 00:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_auto_20230601_0042'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estadisticas',
            table=None,
        ),
    ]
