# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2023-06-03 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_auto_20230602_1630'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empresa',
            table='empresas',
        ),
    ]
